version: "2"
exclude_patterns:
  - "**.css"
  - "**.erb"
  - "**.haml"
  - "**.js"
  - "**.svg"
  - "**.woff"
  - "**/credo/"
  - "**/assets/"
  - "**/vendor/"
  - "**/views/"
  - "bin/"
  - "config/"
  - "db/"
  - "db_redshift/"
  - "docker/"
  - "features/"
  - "public/"
  - "script/"
  - "spec/"
engines:
  bundler-audit:
    enabled: true
engines:
  rubocop:
    channel: rubocop-0-50
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
      - HACK

ratings:
  paths:
    - "app/**/*.rb"
    - "lib/**/*.rb"
    - "engines/**/*.rb"
    - Gemfile.lock
