prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/efueger/credo/master/.rubocop.codeclimate.yml"

prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/efueger/credo/master/.rubocop.default.yml"
    path: ".rubocop.final.yml"


# version: "2"
exclude_paths:
  - "**.css"
  - "**.erb"
  - "**.haml"
  - "**.js"
  - "**.svg"
  - "**.woff"
  - "bin/"
  - "config/"
  - "db/"
  - "db_redshift/"
  - "docker/"
  - "features/"
  - "public/"
  - "script/"
  - "spec/"
engines:
  bundler-audit:
    enabled: false
  rubocop:
    enabled: true
    config:
      file: .rubocop.codeclimate.yml
ratings:
  paths:
    - "app/**/*.rb"
    - "lib/**/*.rb"
    - "engines/**/*.rb"
    - Gemfile.lock
